FROM fedora:latest
ENV USER "$USER"
RUN dnf install -y sudo net-tools less vim procps mariadb mariadb-server
COPY docker-mysql-entrypoint.sh /usr/local/bin/
ENTRYPOINT /usr/local/bin/docker-mysql-entrypoint.sh
